### ISSUE TITLE
End to End Test Course Yamls

### ISSUE THREAD

**Issue by endzyme** [reactiveops/reckoner#28]
It would be great to have some tests for specific features in course.yml or at least basic and complex course.yml files for running blackbox end-to-end testing.

These would also be useful for testing the CLI contracts of providing files and command line arguments. 

Vision:
- test_basic_course.yml (installs one chart with only variables and no helm default args)
- test_advanced_course.yml (installs two+ charts with values, yaml files, string-values, etc)

### Deliverable
* Just the course yaml files that can be run locally for manual testing (figure out automation later)

**Comment by endzyme** [comment]
#88 Starts this process - i will leave this issue open to collect some example tests cases for regression testing.

**Comment by endzyme** [comment]
```yaml
repository: stable
minimum_versions:
  helm: 2.13.1
  reckoner: 1.0.1
helm_args:
  - --recreate-pods
repositories:
  incubator:
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
  reactiveops-stable:
    url: https://charts.reactiveops.com/stable
  reactiveops-incubator:
    url: https://charts.reactiveops.com/incubator
charts:
  metrics-server:
    namespace: metrics-server
    version: "2.4.0"
    hooks:
      pre_install:
        - kubectl create ns metrics-server || true
        - kubectl annotate ns metrics-server --overwrite linkerd.io/inject=enabled --overwrite
    set-values:
      args:
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
        - --metric-resolution=30s
        - --v=3
  rbac-manager:
    namespace: rbac-manager
    version: 0.2.1
    repository: reactiveops-stable
    hooks:
      pre_install:
        - kubectl create ns rbac-manager || true
        - kubectl annotate ns rbac-manager --overwrite linkerd.io/inject=enabled
        - kubectl annotate ns rbac-manager image-whitelist='^quay/.+' --overwrite
      post_install:
      - kubectl apply -f rbacdefinition.yaml
  nginx-ingress:
    chart: nginx-ingress
    namespace: nginx-ingress
    version: 1.3.1
    hooks:
      pre_install:
        - kubectl create ns nginx-ingress || true
        - kubectl annotate ns nginx-ingress --overwrite linkerd.io/inject=enabled
        - kubectl -n nginx-ingress apply -f custom-headers.yaml
    set-values:
      controller.minAvailable: 1
      controller.replicaCount: 2
      defaultBackend.replicaCount: 2
      defaultBackend.minAvailable: 1
      controller.ingressClass: "nginx-ingress"
      controller.publishService.enabled: "true"
      controller.metrics.enabled: true
      controller.stats.enabled: true
      controller.resources:
        limits.cpu: 500m
        limits.memory: 500Mi
        requests.cpu: 100m
        requests.memory: 100Mi
      rbac.create: true
      controller.podLabels.nginx-affinity: nginx-ingress
      controller.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].key: nginx-affinity
      controller.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].operator: In
      controller.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].values[0]: nginx-ingress
      controller.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: "kubernetes.io/hostname"
      controller.image.pullPolicy: "Always"
    values-strings:
      controller.livenessProbe.initialDelaySeconds: 900
      controller:
        extraArgs:
          v: 2
        config:
          add-headers: "nginx-ingress/custom-headers"
```
