### ISSUE TITLE
 [FEATURE REQUEST] - Chart Dependencies 

### ISSUE THREAD

**Issue by ejether** [reactiveops/reckoner#4]
Carried over from: https://github.com/reactiveops/autohelm/issues/47

**Comment by endzyme** [comment]
I'm thinking an MVP for this would be weights or priority levels perhaps. So we could use something like a `priority-group` to denote systems that are ordered into groups but loosely ordered within the group. 

```
charts:
  my-chart-last:
    priority-group: 10
  my-chart-first-ish:
    priority-group: 1
  my-also-first-chart:
    priority-group: 1
  in-between-first-and-last:
    priority-group: 3
```

Thoughts?
