### ISSUE TITLE
A Failing Pre-Install hooks should block chart install 

### ISSUE THREAD

**Issue by endzyme** [reactiveops/reckoner#76]
Currently the behavior of reckoner is to continue on if any of the pre or post installation hooks fail. This can be a confusing user experience, especially if you've fired 20 chart installs and the first one had a failure. This signal can be lost in the noise of output from Reckoner. 

Feature Request
- Could Reckoner, by default, stop after the first failed pre-install hook and notify the customer.
- Could we add a quick summary of failed chart installations at the end of the run (failed chart install N shouldn't block chart N+1)
- Could we add an override to ignore all failed pre-install-hooks
- Failed post-install hooks should also be added to the summary list of failed chart installs as "Failed  Post-Install"
- All hooks should stop running after the first one fails (example below)

```yaml
charts:
  my-chart:
    set-values:
      enabled: true
    hooks:
      pre_install:
        - echo true
        - curl non*possible().domain
        - echo true   #<--- this should never fire if the curl above fails & chart will also not be installed
      post_install:
        - echo true
        - cat fileno-existy
        - echo this-never-runs-in-post
```
